---
- hosts: all
  gather_facts: false # remove later! speeds up testing
  become: true
  roles:
    - deploy_common

- hosts: frontends
  gather_facts: false # remove later! speeds up testing
  become: true
  roles:
    - deploy_haproxy

- hosts: apps
  gather_facts: false
  become: true
  roles:
    - deploy_tomcat
    - deploy_apache

- hosts: appdbs
  become: true
  roles:
    - geerlingguy.postgresql

